name: Add to GitHub Releases

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant Gradlew Permissions
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: shadowJar

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Add Jar to GitHub releases
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.TOKEN_GITHUB }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Automatic Build"
          files: |
            velocity.extension/build/libs/*.jar
            proxy.api/build/libs/*.jar
            loader/build/libs/*.jar
            commons/build/libs/*.jar
            packer/build/libs/*.jar
            service.auctionhouse/build/libs/*.jar
            service.bazaar/build/libs/*.jar
            service.itemtracker/build/libs/*.jar
            service.api/build/libs/*.jar
            service.datamutex/build/libs/*.jar
            service.party/build/libs/*.jar
