name: Build on Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 25
        uses: actions/setup-java@v5.1.0
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Grant Gradlew Permissions
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build with Gradle
        run: ./gradlew shadowJar

      - name: Upload built jars to current release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            velocity.extension/build/libs/*.jar
            proxy.api/build/libs/*.jar
            loader/build/libs/*.jar
            commons/build/libs/*.jar
            packer/build/libs/*.jar
            service.auctionhouse/build/libs/*.jar
            service.bazaar/build/libs/*.jar
            service.itemtracker/build/libs/*.jar
            service.api/build/libs/*.jar
            service.datamutex/build/libs/*.jar
            service.party/build/libs/*.jar
            service.orchestrator/build/libs/*.jar
            service.friend/build/libs/*.jar
            service.darkauction/build/libs/*.jar
